apiVersion: v1
kind: Pod
metadata:
  name: config-secret-demo
spec:
  containers:
  - name: app-container
    image: nginx  # Replace with your application image if needed
    env:
    - name: APP_ENV
      valueFrom: # replace valueFrom with envFrom in case you want to refer to the whole config map file instead of a specific key value and give only config-map name. 
        configMapKeyRef:
          name: app-config
          key: APP_ENV       # Here we are referring to a specific key that need to fetch from the config map
    - name: APP_LOG_LEVEL
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_LOG_LEVEL
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: DB_USER
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: DB_PASSWORD
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
    - name: secret-volume
      mountPath: /etc/secret
  volumes:
  - name: config-volume
    configMap:
      name: app-config
  - name: secret-volume
    secret:
      secretName: db-secret
