apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque 
data:
  DB_USER: YWRtaW4=
  DB_PASSWORD: c2VjcmV0cGFzc3dvcmQ=

---

if you want to store and TLS certs and private keys

apiVersion: v1
kind: Secret
metadata:
  name: my-tls-secret
type: kubernetes.io/tls
data:
  tls.crt: base64_encoded_certificate
  tls.key: base64_encoded_private_key

---
if you want to store Docker registry credentials Required for pulling private images from a Docker registry

apiVersion: v1
kind: Secret
metadata:
  name: my-docker-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: base64_encoded_docker_config
