apiVersion: apps/v1
kind: DeamonSet
metadata:
  name: nginx-ds
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
