apiVersion: v1
kind: Pod
metadata:
  name: multicontainer
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  - name: busybox
    image: busybox
    command: ["sh", "-c", "while true; do echo Hello from BusyBox; sleep 2; done"]
