apiVersion: apps/v1
kind: Deployment
metadata:
  name: recreate-deployment
  labels:
    app: myapp
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: my-app-container
        image: nginx:1.21.1
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: prod
  labels:
    role: web-service
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
  - port: 80
