apiVersion: v1
kind: Pod
metadata:
  name: port-conflict-demo
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80
  - name: busybox-container
    image: busybox
    command: ["sh", "-c", "nc -l -p 80"]
