apiVersion: v1
kind: Pod
metadata:
  name: multicontainer
  namespace: staging
  labels:
    env: staging
	app: busybox
	web: apache
spec:
  containers:
  - name: apache
    image: httpd
    ports:
    - containerPort: 80
  - name: busybox
    image: busybox
    command: ["sh", "-c", "while true; do echo Hello from BusyBox; sleep 2; done"]
