apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: demo-cluster
  region: ap-south-1
  version: "1.30"
vpc:
  id: vpc-0980a4837dd1923b8                    # Give your vpc id and subnet id
  subnets:
    public:
      us-east-1a:
        id: subnet-0957600bb2aec2c32
      us-east-1b:
        id: subnet-0fea65ac64d71bf22
      us-east-1c:
        id: subnet-0e6fc39946077a5a5
managedNodeGroups:
  - name: managed-nodegroup-1
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    ssh:
      publicKeyName: kubeadm
    amiFamily: AmazonLinux2
    volumeSize: 8
    privateNetworking: false
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        cloudWatch: true
        certManager: true
        ebs: true
        fsx: true
        efs: true
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
