apiVersion: v1
kind: Pod
metadata:
  name: webserver
  namespace: prod
  labels:
    env: dev
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: prod
  labels:
    role: web-service
spec:
  selector:
    env: dev
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 80
