# MaxSurge means The number of pod that you want to bring up before terminating the old pods
# maxUnavailable it means  the maximum number of Pods that can be unavailable during the update process.
# revisionHistoryLimit means how many old ReplicaSets (revisions) for the Deployment you want to be retained. 
# minReadySeconds means the minimum number of seconds a newly created Pod has to be ready without crashing or being restarted.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  strategy:
    type: RollingUpdate #Bydefault (RollingUpdate/Recreate)
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  revisionHistoryLimit: 10
  replicas: 6
  minReadySeconds: 10
  selector:
    matchLabels:
      role: webserver
    matchExpressions:
      - {key: version, operator: In, values: [v1, v2, v3]}
  template:
    metadata:
      name: web
      labels:
        role: webserver
        version: v3
        tier: front
    spec:
      containers:
      - name: web
        image: nginx:1.20-perl
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    role: web-service
spec:
  selector:
    role: webserver
  type: NodePort
  ports:
  - port: 80  
