apiVersion: v1
kind: Pod
metadata:
  name: redis-init-pod
  labels:
    app: myapp  
spec:
  initContainers:
  - name: redis-init
    image: aqualyte/redis-alpine
    args:
    - sh
    - -c
    - while true; do STATUS=$(redis-cli -h redis-service -p 6379 ping); if [ $STATUS = "PONG" ]; then echo "Connected"; break; else echo "Not connected"; fi; sleep 10; done
  containers:
  - name: main-container
    image: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 80
  type: NodePort
