apiVersion: v1
kind: Pod
metadata:
  name: emptydirpod
spec:
  containers:
  - image: nginx
    name: emptydircontainer
    volumeMounts:
    - mountPath: /data
      name: emptydirvol
  volumes:
  - name: emptydirvol
    emptyDir: {}
