apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce                                         # it means only single node is allowed to perform read and write operations at a time
 #   - ReadOnlyMany                                           it means multiple node can allowed to perform only read operation at a time
 #   - ReadWriteMany                                          it means multiple node are allowed to perform read and write operation at a time
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc
spec:
  volumeName: demo-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

