apiVersion: v1
kind: Pod
metadata:
  name: hosthpath-pod
spec:
  containers:
  - image: nginx
    name: hosthpath-container
    volumeMounts:
    - mountPath: /data
      name: hosthpath-vol
  volumes:
  - name: hosthpath-vol
    hostPath:
      path: /data
      type: DirectoryOrCreate
