apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  containers:
  - image: nginx
    name: nginx-pvc
    volumeMounts:
    - mountPath: /data
      name: pvc-vol
  volumes:
  - name: pvc-vol
    persistentVolumeClaim:
      claimName: demo-pvc
